# Generated by Django 5.1.3 on 2024-12-07 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentaires',
            options={'ordering': ['date_creation']},
        ),
    ]
