# Generated by Django 5.1.3 on 2024-12-12 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_commentaires_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactions',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forumpost'),
        ),
    ]
