# Generated by Django 5.1.3 on 2024-12-06 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaction',
            old_name='utilisateur',
            new_name='autheur',
        ),
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('autheur', 'publication', 'type_reaction')},
        ),
        migrations.AlterField(
            model_name='reaction',
            name='publication',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='home.publication'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reaction',
            name='type_reaction',
            field=models.CharField(choices=[('like', 'Like'), ('jadore', "J'adore"), ('cool', 'Cool'), ('dislike', "J'aime pas")], max_length=50),
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='commentaire',
        ),
    ]
