# Generated by Django 5.1.3 on 2024-12-03 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='Utilisateur',
            new_name='utilisateur',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='Sujet',
            new_name='sujet',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='Utilisateur',
            new_name='utilisateur',
        ),
        migrations.RenameField(
            model_name='sujet',
            old_name='Utilisateur',
            new_name='utilisateur',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='dislikes',
            field=models.ManyToManyField(related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='jaime',
            field=models.ManyToManyField(related_name='like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='jaime_pas',
            field=models.ManyToManyField(related_name='dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_reaction', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=50)),
                ('date_reaction', models.DateTimeField(auto_now=True)),
                ('commentaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.commentaire')),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.publication')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
