# Generated by Django 5.1.3 on 2024-12-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_utilisateur_commentaire_utilisateur_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentaire',
            options={'ordering': ['-date_mis_a_jour', '-date_creation']},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-date_mis_a_jour', '-date_creation']},
        ),
        migrations.RemoveField(
            model_name='sujet',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='date_mis_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='date_mis_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
